<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>BW2StuffExplorer</AssemblyName>
    <RootNamespace>StuffExplorer</RootNamespace>
    <Version>0.4.0</Version>
    <AssemblyVersion>0.4.0.0</AssemblyVersion>
    <FileVersion>0.4.0.0</FileVersion>
    <ApplicationIcon>Assets\BW2StuffExplorer.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\StuffCore\StuffCore.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\BW2StuffExplorer.ico" />
  </ItemGroup>
</Project>
